version: '3'

services:
  threads-traffic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: threads-traffic
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    ports:
      - "8501:8501"
    environment:
      - TZ=UTC
    command: python main.py --headless
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 1m
      timeout: 10s
      retries: 3 